import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";
import { Resvg } from "@resvg/resvg-js";

const root = fileURLToPath(new URL("../../", import.meta.url));
const read = (name) => readFileSync(resolve(root, name), "utf8");
const write = (name, data) => writeFileSync(resolve(root, name), data);
const png = (svg, width) => new Resvg(svg, width ? { fitTo: { mode: "width", value: width } } : {}).render().asPng();

for (const name of ["dudan-icon", "dudan-wordmark", "dudan-app-icon"]) {
  write(`assets/${name}.png`, png(read(`assets/${name}.svg`)));
}

const drawable = "app/src/main/res/drawable-nodpi";
mkdirSync(resolve(root, drawable), { recursive: true });
// Preserve the supplied paths and gradients; remove the square backdrop for use on app surfaces.
const mark = read("assets/dudan-icon.svg")
  .replace('viewBox="0 0 400 400" width="400" height="400"', 'viewBox="60 25 280 350" width="448" height="560"')
  .replace(/  <rect width="400"[^\n]+\n/, "")
  .replace(/  <ellipse cx="200"[^\n]+\n/, "");
write(`${drawable}/dudan_mark_halo.png`, png(mark));
const plain = mark.replace(/    <g opacity="0\.55" filter="url\(#glow\)">[\s\S]*?<\/g>\s*<\/g>/, "");
write(`${drawable}/dudan_mark.png`, png(plain));

// Android supplies the adaptive mask. Use the app icon's mark without a second rounded tile.
const foreground = read("assets/dudan-app-icon.svg")
  .replace(/^  <rect[^\n]+\n/gm, "")
  .replace(/^    <rect[^\n]+\n/gm, "")
  .replace('<g clip-path="url(#tileClip)">', "<g>");
write(`${drawable}/ic_launcher_foreground.png`, png(foreground, 432));

// White silhouette with a transparent counter, for notification and themed icons.
const silhouette = `
        <path android:fillColor="#FFFFFFFF" android:fillType="evenOdd"
            android:pathData="M333,360 a86,86 0,1 0,172,0 a86,86 0,1 0,-172,0 Z M373,360 a46,46 0,1 0,92,0 a46,46 0,1 0,-92,0 Z" />
        <path android:fillColor="#FFFFFFFF" android:pathData="M466,360 V236 Q466,230 471,227 L506,203 V360 Z" />
        <path android:fillColor="#FFFFFFFF" android:pathData="M393,362 a31,31 0,1 0,62,0 a31,31 0,1 0,-62,0 Z" />`;
const vector = (size, viewport, transform) => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/brand-assets/generate.mjs from the supplied dudan mark. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${size}dp" android:height="${size}dp"
    android:viewportWidth="${viewport}" android:viewportHeight="${viewport}">
    <group ${transform}>${silhouette}
    </group>
</vector>
`;
write("app/src/main/res/drawable/ic_notification.xml", vector(24, 280, 'android:translateX="-279" android:translateY="-184"'));
write("app/src/main/res/drawable/ic_launcher_monochrome.xml", vector(108, 512, 'android:scaleX="1.05" android:scaleY="1.05" android:translateX="-183.95" android:translateY="-78.2"'));
console.log("Generated static PNGs, transparent app marks, adaptive foreground and monochrome icons.");
